package consts

const (
	INTERNAL_URL = "FB_API_INTERNAL_URL"
	PUBLIC_URL   = "FB_API_PUBLIC_URL"
	LISTEN_HOST  = "FB_API_LISTEN_HOST"
	LISTEN_PORT  = "FB_API_LISTEN_PORT"
	LOG_LEVEL    = "FB_LOG_LEVEL"
)
